sudo: false
language: cpp

cache:
 ccache: true
 directories:
  - ~/.local-bin


env:
  global:
    - MAKEFLAGS="-j 2"

matrix:
  include:

    # Latest gcc supported on Travis Linux
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gperf
            - build-essential
            - bison
            - flex
            - libreadline-dev
            - gawk
            - tcl-dev
            - libffi-dev
            - git
            - mercurial
            - graphviz
            - xdot
            - pkg-config
            - python
      env:
        - MATRIX_EVAL="CONFIG=gcc && CC=gcc-7 && CXX=g++-7"

    # Clang which ships on Trusty Linux
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
            - gperf
            - build-essential
            - bison
            - flex
            - libreadline-dev
            - gawk
            - tcl-dev
            - libffi-dev
            - git
            - mercurial
            - graphviz
            - xdot
            - pkg-config
            - python
      env:
        - MATRIX_EVAL="CONFIG=clang && CC=clang-3.8 && CXX=clang++-3.8"

    # Latest clang supported by Travis Linux
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - gperf
            - build-essential
            - bison
            - flex
            - libreadline-dev
            - gawk
            - tcl-dev
            - libffi-dev
            - git
            - mercurial
            - graphviz
            - xdot
            - pkg-config
            - python
      env:
        - MATRIX_EVAL="CONFIG=clang && CC=clang-5.0 && CXX=clang++-5.0"

    # Latest clang on Mac OS X
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="CONFIG=gcc && CC=gcc-7 && CXX=g++-7"

before_install:
  - ./.travis/setup.sh

script:
  - ./.travis/build-and-test.sh

after_success:
  - ./.travis/deploy-after-success.sh
